In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset=pd.read_csv('Untitled spreadsheet - T1.csv')

In [3]:
dataset

,Date/Time,LV ActivePower (kW),Wind Speed (m/s),Wind Direction (Â°),Theoretical_Power_Curve (KWh),Unnamed: 5
0,01 01 2018 00:00,380.047790,5.311336,259.994904,416.328908,NaN
1,01 01 2018 00:10,453.769196,5.672167,268.641113,519.917511,NaN
2,01 01 2018 00:20,306.376587,5.216037,272.564789,390.900016,NaN
3,01 01 2018 00:30,419.645904,5.659674,271.258087,516.127569,NaN
4,01 01 2018 00:40,380.650696,5.577941,265.674286,491.702972,NaN
5,01 01 2018 00:50,402.391998,5.604052,264.578613,499.436385,NaN
6,01 01 2018 01:00,447.605713,5.793008,266.163605,557.372363,NaN
7,01 01 2018 01:10,387.242188,5.306050,257.949493,414.898179,NaN
8,01 01 2018 01:20,463.651215,5.584629,253.480698,493.677652,NaN
9,01 01 2018 01:30,439.725708,5.523228,258.723785,475.706783,NaN
10,01 01 2018 01:40,498.181702,5.724116,251.850998,535.841397,NaN
11,01 01 2018 01:50,526.816223,5.934199,265.504700,603.014076,-
12,01 01 2018 02:00,710.587280,6.547414,274.232910,824.662514,NaN
13,01 01 2018 02:10,655.194275,6.199746,266.733185,693.472641,NaN
14,01 01 2018 02:20,754.762512,6.505383,266.760406,808.098139,NaN
15,01 01 2018 02:30,790.173279,6.634116,270.493195,859.459021,NaN
16,01 01 2018 02:40,742.985291,6.378913,266.593292,759.434537,NaN
17,01 01 2018 02:50,748.229614,6.446653,265.571808,785.281010,NaN
18,01 01 2018 03:00,736.647827,6.415083,261.158691,773.172863,NaN
19,01 01 2018 03:10,787.246216,6.437531,257.560211,781.771216,NaN
20,01 01 2018 03:20,722.864075,6.220024,255.926498,700.764700,NaN
21,01 01 2018 03:30,935.033386,6.898026,250.012894,970.736627,NaN
22,01 01 2018 03:40,1220.609009,7.609711,255.985703,1315.048928,NaN
23,01 01 2018 03:50,1053.771973,7.288356,255.444595,1151.265744,NaN
24,01 01 2018 04:00,1493.807983,7.943102,256.407410,1497.583724,NaN
25,01 01 2018 04:10,1724.488037,8.376162,252.412598,1752.199662,NaN
26,01 01 2018 04:20,1636.935059,8.236958,247.979401,1668.470707,NaN
27,01 01 2018 04:30,1385.488037,7.879591,238.609604,1461.815791,NaN
28,01 01 2018 04:40,1098.932007,7.101376,245.095596,1062.285034,NaN
29,01 01 2018 04:50,1021.458008,6.955307,245.410202,995.995855,NaN
...,...,...,...,...,...,...
50500,31 12 2018 19:00,529.938904,5.197528,97.632187,386.049437,NaN
50501,31 12 2018 19:10,877.915283,5.782113,90.309258,553.935635,NaN
50502,31 12 2018 19:20,711.683228,5.478546,87.520317,462.849436,NaN
50503,31 12 2018 19:30,992.034119,6.146048,84.240913,674.375292,NaN
50504,31 12 2018 19:40,1574.197998,7.936307,78.987038,1493.735939,NaN
50505,31 12 2018 19:50,1706.860962,8.350188,79.042793,1736.454419,NaN
50506,31 12 2018 20:00,1731.552979,8.674524,78.169724,1936.655737,NaN
50507,31 12 2018 20:10,1592.900024,8.135880,78.773773,1608.743387,NaN
50508,31 12 2018 20:20,1403.121948,7.486556,80.061111,1251.008410,NaN
50509,31 12 2018 20:30,1433.415039,7.493729,81.279243,1254.728650,NaN
50510,31 12 2018 20:40,1550.709961,7.724678,79.519127,1376.495123,NaN
50511,31 12 2018 20:50,2062.549072,8.986495,81.056862,2135.288428,NaN
50512,31 12 2018 21:00,2309.875000,9.714014,80.272682,2601.071371,NaN
50513,31 12 2018 21:10,1901.602051,8.498631,79.394409,1827.149165,NaN
50514,31 12 2018 21:20,2240.629883,9.635618,79.356262,2543.911219,NaN
50515,31 12 2018 21:30,1814.355957,8.472826,79.699562,1811.263260,NaN
50516,31 12 2018 21:40,1992.348999,8.433422,80.132507,1787.100338,NaN
50517,31 12 2018 21:50,2554.377930,9.976660,80.081612,2777.504103,NaN
50518,31 12 2018 22:00,2681.270020,10.416830,80.452248,3025.199012,NaN
50519,31 12 2018 22:10,3019.893066,10.713670,80.960693,3161.693967,NaN
50520,31 12 2018 22:20,2771.110107,10.154550,82.335197,2884.512812,NaN
50521,31 12 2018 22:30,3333.819092,12.067660,81.985901,3532.081496,NaN
50522,31 12 2018 22:40,3455.282959,12.195660,82.210617,3549.150371,NaN
50523,31 12 2018 22:50,3429.021973,12.492510,82.111870,3578.567804,NaN
50524,31 12 2018 23:00,3514.269043,12.559170,80.495262,3583.288363,NaN
50525,31 12 2018 23:10,2963.980957,11.404030,80.502724,3397.190793,NaN
50526,31 12 2018 23:20,1684.353027,7.332648,84.062599,1173.055771,NaN
50527,31 12 2018 23:30,2201.106934,8.435358,84.742500,1788.284755,NaN
50528,31 12 2018 23:40,2515.694092,9.421366,84.297913,2418.382503,NaN
50529,31 12 2018 23:50,2820.466064,9.979332,82.274620,2779.184096,NaN

In [4]:
dataset.drop((['Unnamed: 5']),axis=1,inplace=True)
dataset

,Date/Time,LV ActivePower (kW),Wind Speed (m/s),Wind Direction (Â°),Theoretical_Power_Curve (KWh)
0,01 01 2018 00:00,380.047790,5.311336,259.994904,416.328908
1,01 01 2018 00:10,453.769196,5.672167,268.641113,519.917511
2,01 01 2018 00:20,306.376587,5.216037,272.564789,390.900016
3,01 01 2018 00:30,419.645904,5.659674,271.258087,516.127569
4,01 01 2018 00:40,380.650696,5.577941,265.674286,491.702972
5,01 01 2018 00:50,402.391998,5.604052,264.578613,499.436385
6,01 01 2018 01:00,447.605713,5.793008,266.163605,557.372363
7,01 01 2018 01:10,387.242188,5.306050,257.949493,414.898179
8,01 01 2018 01:20,463.651215,5.584629,253.480698,493.677652
9,01 01 2018 01:30,439.725708,5.523228,258.723785,475.706783
10,01 01 2018 01:40,498.181702,5.724116,251.850998,535.841397
11,01 01 2018 01:50,526.816223,5.934199,265.504700,603.014076
12,01 01 2018 02:00,710.587280,6.547414,274.232910,824.662514
13,01 01 2018 02:10,655.194275,6.199746,266.733185,693.472641
14,01 01 2018 02:20,754.762512,6.505383,266.760406,808.098139
15,01 01 2018 02:30,790.173279,6.634116,270.493195,859.459021
16,01 01 2018 02:40,742.985291,6.378913,266.593292,759.434537
17,01 01 2018 02:50,748.229614,6.446653,265.571808,785.281010
18,01 01 2018 03:00,736.647827,6.415083,261.158691,773.172863
19,01 01 2018 03:10,787.246216,6.437531,257.560211,781.771216
20,01 01 2018 03:20,722.864075,6.220024,255.926498,700.764700
21,01 01 2018 03:30,935.033386,6.898026,250.012894,970.736627
22,01 01 2018 03:40,1220.609009,7.609711,255.985703,1315.048928
23,01 01 2018 03:50,1053.771973,7.288356,255.444595,1151.265744
24,01 01 2018 04:00,1493.807983,7.943102,256.407410,1497.583724
25,01 01 2018 04:10,1724.488037,8.376162,252.412598,1752.199662
26,01 01 2018 04:20,1636.935059,8.236958,247.979401,1668.470707
27,01 01 2018 04:30,1385.488037,7.879591,238.609604,1461.815791
28,01 01 2018 04:40,1098.932007,7.101376,245.095596,1062.285034
29,01 01 2018 04:50,1021.458008,6.955307,245.410202,995.995855
...,...,...,...,...,...
50500,31 12 2018 19:00,529.938904,5.197528,97.632187,386.049437
50501,31 12 2018 19:10,877.915283,5.782113,90.309258,553.935635
50502,31 12 2018 19:20,711.683228,5.478546,87.520317,462.849436
50503,31 12 2018 19:30,992.034119,6.146048,84.240913,674.375292
50504,31 12 2018 19:40,1574.197998,7.936307,78.987038,1493.735939
50505,31 12 2018 19:50,1706.860962,8.350188,79.042793,1736.454419
50506,31 12 2018 20:00,1731.552979,8.674524,78.169724,1936.655737
50507,31 12 2018 20:10,1592.900024,8.135880,78.773773,1608.743387
50508,31 12 2018 20:20,1403.121948,7.486556,80.061111,1251.008410
50509,31 12 2018 20:30,1433.415039,7.493729,81.279243,1254.728650
50510,31 12 2018 20:40,1550.709961,7.724678,79.519127,1376.495123
50511,31 12 2018 20:50,2062.549072,8.986495,81.056862,2135.288428
50512,31 12 2018 21:00,2309.875000,9.714014,80.272682,2601.071371
50513,31 12 2018 21:10,1901.602051,8.498631,79.394409,1827.149165
50514,31 12 2018 21:20,2240.629883,9.635618,79.356262,2543.911219
50515,31 12 2018 21:30,1814.355957,8.472826,79.699562,1811.263260
50516,31 12 2018 21:40,1992.348999,8.433422,80.132507,1787.100338
50517,31 12 2018 21:50,2554.377930,9.976660,80.081612,2777.504103
50518,31 12 2018 22:00,2681.270020,10.416830,80.452248,3025.199012
50519,31 12 2018 22:10,3019.893066,10.713670,80.960693,3161.693967
50520,31 12 2018 22:20,2771.110107,10.154550,82.335197,2884.512812
50521,31 12 2018 22:30,3333.819092,12.067660,81.985901,3532.081496
50522,31 12 2018 22:40,3455.282959,12.195660,82.210617,3549.150371
50523,31 12 2018 22:50,3429.021973,12.492510,82.111870,3578.567804
50524,31 12 2018 23:00,3514.269043,12.559170,80.495262,3583.288363
50525,31 12 2018 23:10,2963.980957,11.404030,80.502724,3397.190793
50526,31 12 2018 23:20,1684.353027,7.332648,84.062599,1173.055771
50527,31 12 2018 23:30,2201.106934,8.435358,84.742500,1788.284755
50528,31 12 2018 23:40,2515.694092,9.421366,84.297913,2418.382503
50529,31 12 2018 23:50,2820.466064,9.979332,82.274620,2779.184096

In [5]:
dataset.drop((['Date/Time']),axis=1,inplace=True)
dataset

,LV ActivePower (kW),Wind Speed (m/s),Wind Direction (Â°),Theoretical_Power_Curve (KWh)
0,380.047790,5.311336,259.994904,416.328908
1,453.769196,5.672167,268.641113,519.917511
2,306.376587,5.216037,272.564789,390.900016
3,419.645904,5.659674,271.258087,516.127569
4,380.650696,5.577941,265.674286,491.702972
5,402.391998,5.604052,264.578613,499.436385
6,447.605713,5.793008,266.163605,557.372363
7,387.242188,5.306050,257.949493,414.898179
8,463.651215,5.584629,253.480698,493.677652
9,439.725708,5.523228,258.723785,475.706783
10,498.181702,5.724116,251.850998,535.841397
11,526.816223,5.934199,265.504700,603.014076
12,710.587280,6.547414,274.232910,824.662514
13,655.194275,6.199746,266.733185,693.472641
14,754.762512,6.505383,266.760406,808.098139
15,790.173279,6.634116,270.493195,859.459021
16,742.985291,6.378913,266.593292,759.434537
17,748.229614,6.446653,265.571808,785.281010
18,736.647827,6.415083,261.158691,773.172863
19,787.246216,6.437531,257.560211,781.771216
20,722.864075,6.220024,255.926498,700.764700
21,935.033386,6.898026,250.012894,970.736627
22,1220.609009,7.609711,255.985703,1315.048928
23,1053.771973,7.288356,255.444595,1151.265744
24,1493.807983,7.943102,256.407410,1497.583724
25,1724.488037,8.376162,252.412598,1752.199662
26,1636.935059,8.236958,247.979401,1668.470707
27,1385.488037,7.879591,238.609604,1461.815791
28,1098.932007,7.101376,245.095596,1062.285034
29,1021.458008,6.955307,245.410202,995.995855
...,...,...,...,...
50500,529.938904,5.197528,97.632187,386.049437
50501,877.915283,5.782113,90.309258,553.935635
50502,711.683228,5.478546,87.520317,462.849436
50503,992.034119,6.146048,84.240913,674.375292
50504,1574.197998,7.936307,78.987038,1493.735939
50505,1706.860962,8.350188,79.042793,1736.454419
50506,1731.552979,8.674524,78.169724,1936.655737
50507,1592.900024,8.135880,78.773773,1608.743387
50508,1403.121948,7.486556,80.061111,1251.008410
50509,1433.415039,7.493729,81.279243,1254.728650
50510,1550.709961,7.724678,79.519127,1376.495123
50511,2062.549072,8.986495,81.056862,2135.288428
50512,2309.875000,9.714014,80.272682,2601.071371
50513,1901.602051,8.498631,79.394409,1827.149165
50514,2240.629883,9.635618,79.356262,2543.911219
50515,1814.355957,8.472826,79.699562,1811.263260
50516,1992.348999,8.433422,80.132507,1787.100338
50517,2554.377930,9.976660,80.081612,2777.504103
50518,2681.270020,10.416830,80.452248,3025.199012
50519,3019.893066,10.713670,80.960693,3161.693967
50520,2771.110107,10.154550,82.335197,2884.512812
50521,3333.819092,12.067660,81.985901,3532.081496
50522,3455.282959,12.195660,82.210617,3549.150371
50523,3429.021973,12.492510,82.111870,3578.567804
50524,3514.269043,12.559170,80.495262,3583.288363
50525,2963.980957,11.404030,80.502724,3397.190793
50526,1684.353027,7.332648,84.062599,1173.055771
50527,2201.106934,8.435358,84.742500,1788.284755
50528,2515.694092,9.421366,84.297913,2418.382503
50529,2820.466064,9.979332,82.274620,2779.184096

In [6]:
dataset.isnull().any()

LV ActivePower (kW)              False
Wind Speed (m/s)                 False
Wind Direction (Â°)               False
Theoretical_Power_Curve (KWh)    False
dtype: bool

In [7]:
x=dataset.iloc[:,0:3].values
x

array([[ 380.0477905 ,    5.31133604,  259.9949036 ],
       [ 453.7691956 ,    5.67216682,  268.6411133 ],
       [ 306.3765869 ,    5.2160368 ,  272.5647888 ],
       ...,
       [2201.106934  ,    8.43535805,   84.74250031],
       [2515.694092  ,    9.42136574,   84.2979126 ],
       [2820.466064  ,    9.97933197,   82.27462006]])

In [8]:
y=dataset.iloc[:,3:4].values
y

array([[ 416.3289078],
       [ 519.9175111],
       [ 390.9000158],
       ...,
       [1788.284755 ],
       [2418.382503 ],
       [2779.184096 ]])

In [9]:
from sklearn.model_selection import train_test_split

In [34]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)
x_test

array([[ 576.6569824 ,    5.95249605,   73.27832794],
       [1619.301025  ,    8.13491821,   57.53897858],
       [1876.581055  ,    8.20711517,  254.491394  ],
       ...,
       [ 667.2570801 ,    6.27890301,  124.689003  ],
       [3473.522949  ,   12.08922958,   29.65011024],
       [2343.063965  ,   10.31402969,   60.25027847]])

In [11]:
x_train

array([[4.80995300e+02, 5.55901813e+00, 6.65902023e+01],
       [1.39622803e+03, 7.29126978e+00, 2.59322605e+01],
       [0.00000000e+00, 3.48792696e+00, 1.73011093e+02],
       ...,
       [3.03163599e+03, 1.11938000e+01, 6.44141312e+01],
       [7.30650085e+02, 6.43809509e+00, 7.30249863e+01],
       [3.60444897e+03, 1.45308905e+01, 2.08179398e+02]])

In [12]:
y_train

array([[ 486.1388421 ],
       [1152.690704  ],
       [  50.65948018],
       ...,
       [3336.659665  ],
       [ 781.9879963 ],
       [3600.        ]])

In [13]:
from sklearn.linear_model import LinearRegression
mr = LinearRegression()

In [14]:
mr.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [15]:
y_predict =mr.predict(x_test)

In [16]:
y_predict

array([[ 873.79249176],
       [1779.68261449],
       [1843.49487151],
       ...,
       [ 949.14715813],
       [3401.54611663],
       [2501.2783914 ]])

In [17]:
mr.predict([[380.047790,5.311336,259.994904]])

array([[586.17505819]])

In [18]:
from sklearn.metrics import r2_score
r2_score(y_test,y_predict)

0.9390543482127054

# decision tree

In [19]:
from sklearn.model_selection import train_test_split                #previously cros_validation was used in sklearn
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [20]:
x_train

array([[4.80995300e+02, 5.55901813e+00, 6.65902023e+01],
       [1.39622803e+03, 7.29126978e+00, 2.59322605e+01],
       [0.00000000e+00, 3.48792696e+00, 1.73011093e+02],
       ...,
       [3.03163599e+03, 1.11938000e+01, 6.44141312e+01],
       [7.30650085e+02, 6.43809509e+00, 7.30249863e+01],
       [3.60444897e+03, 1.45308905e+01, 2.08179398e+02]])

In [21]:
from sklearn.tree import DecisionTreeRegressor
regressor= DecisionTreeRegressor(random_state=0)
regressor.fit(x_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=0, splitter='best')

In [22]:
y_predict =regressor.predict(x_test)

In [23]:
y_predict

array([ 609.047533 , 1607.732775 , 1650.624994 , ...,  722.1880659,
       3534.759218 , 2972.303589 ])

In [24]:
regressor.predict([[380.0477905 , 5.31133604, 259.9949036]])

array([416.3289078])

In [36]:
from sklearn.metrics import r2_score
r2_score(y_test,y_predict)

0.9999999865480849

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [27]:
x_train

array([[4.80995300e+02, 5.55901813e+00, 6.65902023e+01],
       [1.39622803e+03, 7.29126978e+00, 2.59322605e+01],
       [0.00000000e+00, 3.48792696e+00, 1.73011093e+02],
       ...,
       [3.03163599e+03, 1.11938000e+01, 6.44141312e+01],
       [7.30650085e+02, 6.43809509e+00, 7.30249863e+01],
       [3.60444897e+03, 1.45308905e+01, 2.08179398e+02]])

In [28]:
x_test.shape

(10106, 3)

In [29]:
x_train

array([[4.80995300e+02, 5.55901813e+00, 6.65902023e+01],
       [1.39622803e+03, 7.29126978e+00, 2.59322605e+01],
       [0.00000000e+00, 3.48792696e+00, 1.73011093e+02],
       ...,
       [3.03163599e+03, 1.11938000e+01, 6.44141312e+01],
       [7.30650085e+02, 6.43809509e+00, 7.30249863e+01],
       [3.60444897e+03, 1.45308905e+01, 2.08179398e+02]])

In [30]:
x_train.shape

(40424, 3)

In [31]:
from sklearn.ensemble import RandomForestRegressor
Regressor=RandomForestRegressor(n_estimators=10,criterion='mse',random_state=0)

In [32]:
regressor.fit(x_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=0, splitter='best')

In [33]:
y_predict=regressor.predict(x_test)
y_predict

array([ 609.047533 , 1607.732775 , 1650.624994 , ...,  722.1880659,
       3534.759218 , 2972.303589 ])

In [35]:
from sklearn.metrics import r2_score
r2_score(y_test,y_predict)

0.9999999865480849